def foo():
    a = 1

foo()
print(a) #오류 발생 